[package]
name = "my_program"
version = "0.1.0"
authors = ["Doug Hodson <doug@sidechannel.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "my_program"
path = "main.rs"
